// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb2CYLN_uSuYJ_qUfwtupX-vrGDYfYLWw',
    appId: '1:331296160504:android:b0d6b4f6189448660f590d',
    messagingSenderId: '331296160504',
    projectId: 'instaclone-ce105',
    storageBucket: 'instaclone-ce105.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbWi-HPFZNtkuhhmz7k037GCrGE3krPME',
    appId: '1:331296160504:ios:3d026fa6d609f2fb0f590d',
    messagingSenderId: '331296160504',
    projectId: 'instaclone-ce105',
    storageBucket: 'instaclone-ce105.appspot.com',
    iosClientId: '331296160504-47frf8tr05racqblrdenu4828ai2hsri.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
